services:
  db:
    container_name: currency-pg
    image: postgres:15
    environment:
      POSTGRES_USER: currency
      POSTGRES_PASSWORD: currency
      POSTGRES_DB: converterdb
    ports:
      - "5433:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U currency -d converterdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: